FROM golang:latest AS builder

WORKDIR /grpc

COPY ./go.mod go.mod
COPY ./go.sum go.sum
COPY ./server.go main.go

ENV GO111MODULE=on

RUN go mod tidy -compat=1.22.4
RUN CGO_ENABLED=0 GOOOS=linux go build -o /grpc/server

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /grpc/server ./grpc_server

CMD ["/root/grpc_server"]
