#!/bin/bash

printenv

sed -e "s|subst\.PORT|${PORT}|g" \
    -e "s|subst\.GRPC_HOST|${GRPC_HOST}|g" \
    -e "s|subst\.GRPC_PORT|${GRPC_PORT}|g" \
    /etc/envoy/envoy.yaml > /tmp/envoy.yaml

cat -n /tmp/envoy.yaml

envoy -c /tmp/envoy.yaml --log-level debug
